name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'app/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip backend folder
        run: |
          cd app/backend
          zip -r backend.zip .

      - name: Upload backend.zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'app/backend/backend.zip'
          target: '/home/ubuntu/'

      - name: Deploy Backend on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.EC2_BACKEND_PATH }}
            unzip -o ~/backend.zip -d ${{ secrets.EC2_BACKEND_PATH }}
            cd ${{ secrets.EC2_BACKEND_PATH }}
            npm install
            npm run build
            pm2 restart backend || pm2 start dist/main.js --name backend
