name: Deploy Backend (NestJS)

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip backend folder
        run: |
          cd app
          zip -r backend.zip backend

      - name: Upload backend.zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: 'app/backend.zip'
          target: ${{ secrets.EC2_BACKEND_PATH }}

      - name: Deploy Backend on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.EC2_BACKEND_PATH }}
            rm -rf backend
            unzip backend.zip
            mv backend/* .
            rm -rf backend backend.zip

            npm install --production
            npm run build

            pm2 start pm2.config.js --update-env || pm2.restart backend
            pm2 save
