name: Deploy Frontend (Next.js)

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Zip frontend folder
        run: |
          cd app
          zip -r frontend.zip frontend

      - name: Upload frontend.zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: 'app/frontend.zip'
          target: ${{ secrets.EC2_FRONTEND_PATH }}

      - name: Deploy Frontend on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.EC2_FRONTEND_PATH }}
            rm -rf frontend
            unzip frontend.zip
            mv frontend/* .
            rm -rf frontend frontend.zip

            npm install --production
            npm run build

            pm2 start pm2.config.js --update-env || pm2 restart frontend
            pm2 save
